name: Deploy to Server
on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    outputs:
      salida: ${{ steps.step_1.outputs.my_variable }}
    steps:
      - name: Generar archivo
        run: echo "Archivo prueba, hola" >> test.log
      - name: Subir artefacto
        uses: actions/upload-artifact@v3
        with:
          name: archivo-test
          path: test.log