name: Deploy to Server
on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    outputs:
      salida: ${{ steps.step_1.outputs.my_variable }}
    steps:
      - name: Working dir
        id: step_1
        run: echo "my_variable=Hola Mundo" >> $GITHUB_OUTPUT
      - name: Obtener mensaje
        run: echo "${{ steps.step_1.outputs.my_variable }}"

  second_job:
    runs-on: ubuntu-latest
    needs: first_job

    env:
      SALIDA: ${{ needs.first_job.outputs.salida }}

    steps:
      - name: Hola Mundo
        run: 'echo "Hola Mundo: ${{ github.ref }} y msje salida: ${{ env.SALIDA }}"'